const stringArray = { type: 'array', items: { type: 'string' } } as const;

const analysisSectionSchema = {
  type: 'object',
  additionalProperties: false,
  properties: {
    rfpFact: stringArray,
    aiProposal: stringArray,
    confirmNeeded: stringArray,
  },
  required: ['rfpFact', 'aiProposal', 'confirmNeeded'],
} as const;

export const analysisJsonSchema = {
  type: 'object',
  additionalProperties: false,
  properties: {
    projectOverview: { type: 'string' },
    clientChallenge: { type: 'string' },
    requiredItems: stringArray,
    constraints: stringArray,
    targetInfo: { type: 'string' },
    spatialCondition: { type: 'string' },
    contentCondition: { type: 'string' },
    operationCondition: { type: 'string' },
    kpiScheduleConstraints: stringArray,
    missingInfo: stringArray,
    rfpRequirements: analysisSectionSchema,
    clientTask: analysisSectionSchema,
    targetSpaceContentOperation: analysisSectionSchema,
    kpiTimelineConstraints: analysisSectionSchema,
  },
  required: [
    'projectOverview',
    'clientChallenge',
    'requiredItems',
    'constraints',
    'targetInfo',
    'spatialCondition',
    'contentCondition',
    'operationCondition',
    'kpiScheduleConstraints',
    'missingInfo',
    'rfpRequirements',
    'clientTask',
    'targetSpaceContentOperation',
    'kpiTimelineConstraints',
  ],
} as const;


export const conceptCandidatesJsonSchema = {
  type: 'object',
  additionalProperties: false,
  properties: {
    concepts: {
      type: 'array',
      minItems: 3,
      maxItems: 3,
      items: {
        type: 'object',
        additionalProperties: false,
        properties: {
          conceptId: { type: 'string' },
          conceptNameKR: { type: 'string' },
          conceptNameEN: { type: 'string' },
          oneLineDefinition: { type: 'string' },
          coreMessage: { type: 'string' },
          experienceLogic: { type: 'string' },
          targetRelevance: { type: 'string' },
          keyExperienceAssetDirection: { type: 'string' },
          whyThisWorks: { type: 'string' },
        },
        required: [
          'conceptId',
          'conceptNameKR',
          'conceptNameEN',
          'oneLineDefinition',
          'coreMessage',
          'experienceLogic',
          'targetRelevance',
          'keyExperienceAssetDirection',
          'whyThisWorks',
        ],
      },
    },
  },
  required: ['concepts'],
} as const;

export const outlineJsonSchema = {
  type: 'object',
  additionalProperties: false,
  properties: {
    slides: {
      type: 'array',
      minItems: 20,
      maxItems: 60,
      items: {
        type: 'object',
        additionalProperties: false,
        properties: {
          slideNumber: { type: 'number' },
          slideType: { type: 'string' },
          slideTitle: { type: 'string' },
          slidePurpose: { type: 'string' },
          keyMessage: { type: 'string' },
          confirmNeededNote: { type: 'string' },
        },
        required: ['slideNumber', 'slideType', 'slideTitle', 'slidePurpose', 'keyMessage', 'confirmNeededNote'],
      },
    },
  },
  required: ['slides'],
} as const;


const productExperienceDetailSchema = {
  type: 'object',
  additionalProperties: false,
  properties: {
    productCode: { type: 'string' },
    productNameOrRole: { type: 'string' },
    coreValue: { type: 'string' },
    experienceTitle: { type: 'string' },
    oneLineExperience: { type: 'string' },
    visitorMission: { type: 'string' },
    visitorAction: { type: 'string' },
    contentMechanism: { type: 'string' },
    mediaOrObject: { type: 'string' },
    spatialPlacement: { type: 'string' },
    outputOrReward: { type: 'string' },
    snsSharePoint: { type: 'string' },
    visualDirection: { type: 'string' },
    imagePlaceholder: { type: 'string' },
    diagramSuggestion: { type: 'string' },
  },
  required: [
    'productCode',
    'productNameOrRole',
    'coreValue',
    'experienceTitle',
    'oneLineExperience',
    'visitorMission',
    'visitorAction',
    'contentMechanism',
    'mediaOrObject',
    'spatialPlacement',
    'outputOrReward',
    'snsSharePoint',
    'visualDirection',
    'imagePlaceholder',
    'diagramSuggestion',
  ],
} as const;

const keyExperienceAssetSchema = {
  type: 'object',
  additionalProperties: false,
  properties: {
    assetName: { type: 'string' },
    assetType: { type: 'string' },
    roleInProposal: { type: 'string' },
    visitorAction: { type: 'string' },
    experienceMechanism: { type: 'string' },
    spatialPlacement: { type: 'string' },
    mediaOrObject: { type: 'string' },
    outputOrReward: { type: 'string' },
    whyItMatters: { type: 'string' },
    visualDirection: { type: 'string' },
  },
  required: [
    'assetName',
    'assetType',
    'roleInProposal',
    'visitorAction',
    'experienceMechanism',
    'spatialPlacement',
    'mediaOrObject',
    'outputOrReward',
    'whyItMatters',
    'visualDirection',
  ],
} as const;

const experienceScenarioStepSchema = {
  type: 'object',
  additionalProperties: false,
  properties: {
    step: { type: 'string', enum: ['Entry', 'Select', 'Experience', 'Generate', 'Share', 'Exit'] },
    visitorAction: { type: 'string' },
    systemResponse: { type: 'string' },
    mediaOrObject: { type: 'string' },
    output: { type: 'string' },
    designNote: { type: 'string' },
  },
  required: ['step', 'visitorAction', 'systemResponse', 'mediaOrObject', 'output', 'designNote'],
} as const;

export const slideContentJsonSchema = {
  type: 'object',
  additionalProperties: false,
  properties: {
    slides: {
      type: 'array',
      minItems: 20,
      maxItems: 60,
      items: {
        type: 'object',
        additionalProperties: false,
        properties: {
          slideNumber: { type: 'number' },
          slideType: { type: 'string' },
          slideTitle: { type: 'string' },
          slidePurpose: { type: 'string' },
          keyMessage: { type: 'string' },
          mainCopy: { type: 'string' },
          bodyBullets: { type: 'array', minItems: 3, maxItems: 7, items: { type: 'string' } },
          visualDirection: { type: 'string' },
          visitorAction: { type: 'string' },
          contentMechanism: { type: 'string' },
          spatialPlacement: { type: 'string' },
          mediaOrObject: { type: 'string' },
          outputOrReward: { type: 'string' },
          imagePlaceholder: { type: 'string' },
          visualPrompt: { type: 'string' },
          diagramSuggestion: { type: 'string' },
          productExperienceDetails: { type: 'array', items: productExperienceDetailSchema },
          keyExperienceAssets: { type: 'array', maxItems: 3, items: keyExperienceAssetSchema },
          experienceScenarioSteps: { type: 'array', items: experienceScenarioStepSchema },
          speakerNote: { type: 'string' },
          confirmNeededNote: { type: 'string' },
        },
        required: [
          'slideNumber',
          'slideType',
          'slideTitle',
          'slidePurpose',
          'keyMessage',
          'mainCopy',
          'bodyBullets',
          'visualDirection',
          'visitorAction',
          'contentMechanism',
          'spatialPlacement',
          'mediaOrObject',
          'outputOrReward',
          'imagePlaceholder',
          'visualPrompt',
          'diagramSuggestion',
          'productExperienceDetails',
          'keyExperienceAssets',
          'experienceScenarioSteps',
          'speakerNote',
          'confirmNeededNote',
        ],
      },
    },
  },
  required: ['slides'],
} as const;
