const stringArray = { type: 'array', items: { type: 'string' } } as const;


const slidePurposeEnum = ['Problem', 'Insight', 'Strategy', 'Concept', 'Experience', 'Content', 'Proof', 'Impact'] as const;


const entityDifferentiationItemSchema = {
  type: 'object',
  additionalProperties: false,
  properties: {
    entityName: { type: 'string' },
    entityType: { type: 'string' },
    sourceEvidence: { type: 'string' },
    roleInProject: { type: 'string' },
    keyOffering: { type: 'string' },
    audienceTakeaway: { type: 'string' },
    distinctMessage: { type: 'string' },
    proofPoint: { type: 'string' },
    spatialOrContentRole: { type: 'string' },
    experienceMechanism: { type: 'string' },
    visualOrToneCue: { type: 'string' },
    relationshipToOtherEntities: { type: 'string' },
    riskIfUndifferentiated: { type: 'string' },
  },
  required: ['entityName', 'entityType', 'sourceEvidence', 'roleInProject', 'keyOffering', 'audienceTakeaway', 'distinctMessage', 'proofPoint', 'spatialOrContentRole', 'experienceMechanism', 'visualOrToneCue', 'relationshipToOtherEntities', 'riskIfUndifferentiated'],
} as const;

const narrativeFlowStageSchema = {
  type: 'object',
  additionalProperties: false,
  properties: {
    stage: { type: 'string' },
    purpose: { type: 'string' },
  },
  required: ['stage', 'purpose'],
} as const;

export const proposalNarrativeJsonSchema = {
  type: 'object',
  additionalProperties: false,
  properties: {
    marketContext: { type: 'string' },
    coreProblem: { type: 'string' },
    strategicOpportunity: { type: 'string' },
    proposalThesis: { type: 'string' },
    whyNow: { type: 'string' },
    whyUs: { type: 'string' },
    whyThisConcept: { type: 'string' },
    narrativeFlow: { type: 'array', minItems: 5, items: narrativeFlowStageSchema },
    unifyingFrame: { type: 'string' },
    differentiationPrinciple: { type: 'string' },
    entityDifferentiationMatrix: { type: 'array', items: entityDifferentiationItemSchema },
    riskOfOverIntegration: { type: 'string' },
    howToAvoidSimilarity: { type: 'string' },
    currentRfpSpecificity: { type: 'string' },
  },
  required: ['marketContext', 'coreProblem', 'strategicOpportunity', 'proposalThesis', 'whyNow', 'whyUs', 'whyThisConcept', 'narrativeFlow', 'unifyingFrame', 'differentiationPrinciple', 'entityDifferentiationMatrix', 'riskOfOverIntegration', 'howToAvoidSimilarity', 'currentRfpSpecificity'],
} as const;


const taskSectionSchema = {
  type: 'object',
  additionalProperties: false,
  properties: {
    taskId: { type: 'string' },
    taskTitle: { type: 'string' },
    phase: { type: 'string' },
    requiredDeliverables: stringArray,
    target: stringArray,
    keyRequirements: stringArray,
    referenceMentions: stringArray,
    existingAssets: stringArray,
    constraints: stringArray,
    kpi: stringArray,
    schedule: stringArray,
    confirmNeeded: stringArray,
  },
  required: [
    'taskId',
    'taskTitle',
    'phase',
    'requiredDeliverables',
    'target',
    'keyRequirements',
    'referenceMentions',
    'existingAssets',
    'constraints',
    'kpi',
    'schedule',
    'confirmNeeded',
  ],
} as const;



const productFeatureSchema = {
  type: 'object',
  additionalProperties: false,
  properties: {
    product: { type: 'string' },
    keyFeature: { type: 'string' },
    valueProposition: { type: 'string' },
  },
  required: ['product', 'keyFeature', 'valueProposition'],
} as const;

const numericInfoSchema = {
  type: 'object',
  additionalProperties: false,
  properties: {
    pastPerformance: stringArray,
    lessonLearned: stringArray,
    currentIssue: stringArray,
    targetKPI: stringArray,
    referenceMetric: stringArray,
    proposedMeasurement: stringArray,
  },
  required: ['pastPerformance', 'lessonLearned', 'currentIssue', 'targetKPI', 'referenceMetric', 'proposedMeasurement'],
} as const;

const proposalTypeEnum = ['basic', 'cheil', 'innocean', 'hyundai', 'mice_event_operation', 'conference_forum'] as const;
const proposalScopeTypeEnum = ['contentDevelopment', 'boothExhibition', 'experienceMarketing', 'brandActivation', 'operationOnly', 'designBuild', 'publicTender'] as const;

const analysisSectionSchema = {
  type: 'object',
  additionalProperties: false,
  properties: {
    rfpFact: stringArray,
    aiProposal: stringArray,
    confirmNeeded: stringArray,
  },
  required: ['rfpFact', 'aiProposal', 'confirmNeeded'],
} as const;

export const analysisJsonSchema = {
  type: 'object',
  additionalProperties: false,
  properties: {
    projectOverview: { type: 'string' },
    clientChallenge: { type: 'string' },
    taskSections: { type: 'array', items: taskSectionSchema },
    inferredProposalType: { type: 'string', enum: proposalTypeEnum },
    proposalTypeReasoning: { type: 'string' },
    proposalScopeTypes: { type: 'array', items: { type: 'string', enum: proposalScopeTypeEnum } },
    proposalStructureGuard: { type: 'string' },
    requiredDeliverables: stringArray,
    scopeOfWork: stringArray,
    evaluationCriteria: stringArray,
    requiredItems: stringArray,
    requiredScope: stringArray,
    referenceOnly: stringArray,
    existingAssets: stringArray,
    productInfo: stringArray,
    productFeatures: { type: 'array', items: productFeatureSchema },
    kpiObjectives: stringArray,
    numericInfo: numericInfoSchema,
    constraints: stringArray,
    schedule: stringArray,
    doNotTreatAsScope: stringArray,
    confirmNeeded: stringArray,
    targetInfo: { type: 'string' },
    spatialCondition: { type: 'string' },
    contentCondition: { type: 'string' },
    operationCondition: { type: 'string' },
    kpiScheduleConstraints: stringArray,
    missingInfo: stringArray,
    rfpRequirements: analysisSectionSchema,
    clientTask: analysisSectionSchema,
    targetSpaceContentOperation: analysisSectionSchema,
    kpiTimelineConstraints: analysisSectionSchema,
  },
  required: [
    'projectOverview',
    'clientChallenge',
    'taskSections',
    'inferredProposalType',
    'proposalTypeReasoning',
    'proposalScopeTypes',
    'proposalStructureGuard',
    'requiredDeliverables',
    'scopeOfWork',
    'evaluationCriteria',
    'requiredItems',
    'requiredScope',
    'referenceOnly',
    'existingAssets',
    'productInfo',
    'productFeatures',
    'kpiObjectives',
    'numericInfo',
    'constraints',
    'schedule',
    'doNotTreatAsScope',
    'confirmNeeded',
    'targetInfo',
    'spatialCondition',
    'contentCondition',
    'operationCondition',
    'kpiScheduleConstraints',
    'missingInfo',
    'rfpRequirements',
    'clientTask',
    'targetSpaceContentOperation',
    'kpiTimelineConstraints',
  ],
} as const;


const conceptDevelopmentLogicSchema = {
  type: 'object',
  additionalProperties: false,
  properties: {
    winningStrategyBrief: { type: 'string' },
    proposalThesis: { type: 'string' },
    experienceLogic: { type: 'string' },
    clientIntent: { type: 'string' },
    audienceTakeaway: { type: 'string' },
    strategicTension: { type: 'string' },
    conceptSeed: { type: 'string' },
    coreChallenge: { type: 'string' },
    targetInsight: { type: 'string' },
    brandOrProductValue: { type: 'string' },
    experienceOpportunity: { type: 'string' },
    strategicApproach: { type: 'string' },
    conceptNecessity: { type: 'string' },
    selectedConceptReason: { type: 'string' },
  },
  required: [
    'winningStrategyBrief',
    'proposalThesis',
    'experienceLogic',
    'clientIntent',
    'audienceTakeaway',
    'strategicTension',
    'conceptSeed',
    'coreChallenge',
    'targetInsight',
    'brandOrProductValue',
    'experienceOpportunity',
    'strategicApproach',
    'conceptNecessity',
    'selectedConceptReason',
  ],
} as const;


const entityDifferentiationUseSchema = {
  type: 'object',
  additionalProperties: false,
  properties: {
    unifyingFrame: { type: 'string' },
    distinctEntityRoles: { type: 'string' },
    visitorRecognitionLogic: { type: 'string' },
    proofByEntity: { type: 'string' },
    riskCheck: { type: 'string' },
  },
  required: ['unifyingFrame', 'distinctEntityRoles', 'visitorRecognitionLogic', 'proofByEntity', 'riskCheck'],
} as const;

const conceptRationaleSchema = {
  type: 'object',
  additionalProperties: false,
  properties: {
    problemInsight: { type: 'string' },
    clientNeed: { type: 'string' },
    audienceBarrier: { type: 'string' },
    strategicShift: { type: 'string' },
    whyThisConcept: { type: 'string' },
  },
  required: ['problemInsight', 'clientNeed', 'audienceBarrier', 'strategicShift', 'whyThisConcept'],
} as const;


const hiddenNeedsSchema = {
  type: 'object',
  additionalProperties: false,
  properties: {
    surfaceRequest: { type: 'string' },
    hiddenNeed: { type: 'string' },
    clientAnxiety: { type: 'string' },
    decisionTrigger: { type: 'string' },
    evaluationRisk: { type: 'string' },
    realWinningCondition: { type: 'string' },
  },
  required: ['surfaceRequest', 'hiddenNeed', 'clientAnxiety', 'decisionTrigger', 'evaluationRisk', 'realWinningCondition'],
} as const;

const strategicApproachSchema = {
  type: 'object',
  additionalProperties: false,
  properties: {
    strategicTension: { type: 'string' },
    winningApproach: { type: 'string' },
    differentiationLogic: { type: 'string' },
    audiencePerceptionShift: { type: 'string' },
    proofLogic: { type: 'string' },
  },
  required: ['strategicTension', 'winningApproach', 'differentiationLogic', 'audiencePerceptionShift', 'proofLogic'],
} as const;

const keywordExecutionGuideSchema = {
  type: 'object',
  additionalProperties: false,
  properties: {
    keyword: { type: 'string' },
    spatialUXImplication: { type: 'string' },
    designImplication: { type: 'string' },
    contentImplication: { type: 'string' },
    contentOrMediaImplication: { type: 'string' },
    operationImplication: { type: 'string' },
  },
  required: ['keyword', 'spatialUXImplication', 'designImplication', 'contentImplication', 'contentOrMediaImplication', 'operationImplication'],
} as const;

const antiPatternValidationSchema = {
  type: 'object',
  additionalProperties: false,
  properties: {
    riskToAvoid: { type: 'string' },
    howThisConceptAvoidsIt: { type: 'string' },
    validationCheck: { type: 'string' },
    validationCriteria: stringArray,
    passed: { type: 'boolean' },
    validationSummary: { type: 'string' },
  },
  required: ['riskToAvoid', 'howThisConceptAvoidsIt', 'validationCheck', 'validationCriteria', 'passed', 'validationSummary'],
} as const;

const conceptMetaphorSourceSchema = {
  type: 'object',
  additionalProperties: false,
  properties: {
    metaphorSeed: { type: 'string' },
    symbolicImage: { type: 'string' },
    proposalWorld: { type: 'string' },
    whyThisCanBecomeAConceptTitle: { type: 'string' },
    sourceTypes: { type: 'array', minItems: 1, maxItems: 3, items: { type: 'string', enum: ['actual RFP object', 'project type', 'client or brand role', 'product/service logic', 'spatial structure', 'audience behavior', 'content mechanism', 'operational proof', 'evaluation criteria', 'stakeholder relationship'] } },
    rfpEvidence: { type: 'array', minItems: 3, maxItems: 5, items: { type: 'string' } },
  },
  required: ['metaphorSeed', 'symbolicImage', 'proposalWorld', 'whyThisCanBecomeAConceptTitle', 'sourceTypes', 'rfpEvidence'],
} as const;

const conceptMechanismSchema = {
  type: 'object',
  additionalProperties: false,
  properties: {
    experienceMechanism: { type: 'string' },
    spatialMechanism: { type: 'string' },
    contentMechanism: { type: 'string' },
    interactionMechanism: { type: 'string' },
    recognitionLogic: { type: 'string' },
    visitorOrAudienceTransformation: { type: 'string' },
    proofMechanism: { type: 'string' },
    whyThisCanBecomeAConcept: { type: 'string' },
  },
  required: ['experienceMechanism', 'spatialMechanism', 'contentMechanism', 'interactionMechanism', 'recognitionLogic', 'visitorOrAudienceTransformation', 'proofMechanism', 'whyThisCanBecomeAConcept'],
} as const;


const conceptScopeValidationSchema = {
  type: 'object',
  additionalProperties: false,
  properties: {
    coversWholeProposal: { type: 'boolean' },
    coversMainEntitiesOrScope: { type: 'boolean' },
    expandableToSpace: { type: 'boolean' },
    expandableToContent: { type: 'boolean' },
    expandableToMediaOrInteraction: { type: 'boolean' },
    expandableToOperationOrProof: { type: 'boolean' },
    notProductSpecificOnly: { type: 'boolean' },
    notSectionTitleOnly: { type: 'boolean' },
  },
  required: ['coversWholeProposal', 'coversMainEntitiesOrScope', 'expandableToSpace', 'expandableToContent', 'expandableToMediaOrInteraction', 'expandableToOperationOrProof', 'notProductSpecificOnly', 'notSectionTitleOnly'],
} as const;

const conceptNameScopeClassificationEnum = ['proposal_level', 'section_level', 'content_module_level', 'product_specific_level', 'generic_label'] as const;

const entityBalanceStatusEnum = ['balanced', 'over-focused', 'unknown'] as const;
const rfpConceptTypeEnum = ['multi_entity_pavilion', 'single_brand_experience', 'visitor_center_or_tour', 'product_experience_space', 'pop_up_or_campaign', 'exhibition_booth', 'content_media_experience', 'operation_heavy_event', 'public_sector_exhibition', 'technology_showcase', 'unknown'] as const;

const conceptEvaluationScoresSchema = {
  type: 'object',
  additionalProperties: false,
  properties: {
    rfpFitScore: { type: 'number', minimum: 1, maximum: 5 },
    targetFitScore: { type: 'number', minimum: 1, maximum: 5 },
    differentiationScore: { type: 'number', minimum: 1, maximum: 5 },
    spatialFeasibilityScore: { type: 'number', minimum: 1, maximum: 5 },
    viralPotentialScore: { type: 'number', minimum: 1, maximum: 5 },
    operationFeasibilityScore: { type: 'number', minimum: 1, maximum: 5 },
  },
  required: [
    'rfpFitScore',
    'targetFitScore',
    'differentiationScore',
    'spatialFeasibilityScore',
    'viralPotentialScore',
    'operationFeasibilityScore',
  ],
} as const;

const winningThesisSchema = {
  type: 'object',
  additionalProperties: false,
  properties: {
    contextShift: { type: 'string' },
    previousBaseline: { type: 'string' },
    newReality: { type: 'string' },
    clientUniquePosition: { type: 'string' },
    audiencePerceptionGap: { type: 'string' },
    winningClaim: { type: 'string' },
    whyNow: { type: 'string' },
    whyThisClient: { type: 'string' },
    whatMustBeProven: { type: 'string' },
  },
  required: ['contextShift', 'previousBaseline', 'newReality', 'clientUniquePosition', 'audiencePerceptionGap', 'winningClaim', 'whyNow', 'whyThisClient', 'whatMustBeProven'],
} as const;

const conceptLeapSchema = {
  type: 'object',
  additionalProperties: false,
  properties: {
    fromStatement: { type: 'string' },
    toStatement: { type: 'string' },
    conceptLeap: { type: 'string' },
    corePromise: { type: 'string' },
    emotionalTakeaway: { type: 'string' },
    evaluatorTakeaway: { type: 'string' },
  },
  required: ['fromStatement', 'toStatement', 'conceptLeap', 'corePromise', 'emotionalTakeaway', 'evaluatorTakeaway'],
} as const;

const signatureProofIdeaSchema = {
  type: 'object',
  additionalProperties: false,
  properties: {
    signatureScene: { type: 'string' },
    signatureContent: { type: 'string' },
    signatureSpatialMove: { type: 'string' },
    signatureMediaOrInteraction: { type: 'string' },
    whyThisProvesTheConcept: { type: 'string' },
    whyThisIsNotGeneric: { type: 'string' },
  },
  required: ['signatureScene', 'signatureContent', 'signatureSpatialMove', 'signatureMediaOrInteraction', 'whyThisProvesTheConcept', 'whyThisIsNotGeneric'],
} as const;


const directionSourceSchema = {
  type: 'object',
  additionalProperties: false,
  properties: {
    rfpEvidence: { type: 'string' },
    proposalPatternLearning: { type: 'string' },
    lostPatternAvoidance: { type: 'string' },
  },
  required: ['rfpEvidence', 'proposalPatternLearning', 'lostPatternAvoidance'],
} as const;

const directionDebugSchema = {
  type: 'object',
  additionalProperties: false,
  properties: {
    source: { type: 'string' },
    failurePatternAvoided: { type: 'string' },
    winningPatternUsed: { type: 'string' },
    confidence: { type: 'string' },
  },
  required: ['source', 'failurePatternAvoided', 'winningPatternUsed', 'confidence'],
} as const;
export const conceptCandidatesJsonSchema = {
  type: 'object',
  additionalProperties: false,
  properties: {
    hiddenNeeds: hiddenNeedsSchema,
    strategicApproach: strategicApproachSchema,
    entityDifferentiationMatrix: { type: 'array', items: entityDifferentiationItemSchema },
    conceptDevelopmentLogic: conceptDevelopmentLogicSchema,
    concepts: {
      type: 'array',
      minItems: 3,
      maxItems: 3,
      items: {
        type: 'object',
        additionalProperties: false,
        properties: {
          conceptId: { type: 'string' },
          rfpConceptType: { type: 'string', enum: rfpConceptTypeEnum },
          secondaryRfpConceptTypes: { type: 'array', items: { type: 'string', enum: rfpConceptTypeEnum } },
          strategicDirectionType: { type: 'string' },
          strategicDirectionLabel: { type: 'string' },
          whatThisDirectionEmphasizes: { type: 'string' },
          whenToChooseThisDirection: { type: 'string' },
          directionSource: directionSourceSchema,
          failurePatternAvoided: { type: 'string' },
          winningPatternUsed: { type: 'string' },
          directionDebug: directionDebugSchema,
          proposalCoreConceptName: { type: 'string' },
          proposalCoreConceptSlogan: { type: 'string' },
          proposalCoreConceptDefinition: { type: 'string' },
          winningThesisUse: winningThesisSchema,
          conceptLeap: conceptLeapSchema,
          signatureProofIdea: signatureProofIdeaSchema,
          whyThisIsCoreConcept: { type: 'string' },
          experiencePrinciple: { type: 'string' },
          visitorJourney: { type: 'string' },
          contentMediaImplication: { type: 'string' },
          conceptName: { type: 'string' },
          conceptSlogan: { type: 'string' },
          conceptTagline: { type: 'string' },
          conceptDefinition: { type: 'string' },
          hiddenNeedResolved: { type: 'string' },
          strategicApproach: { type: 'string' },
          whyThisConcept: { type: 'string' },
          conceptMechanism: conceptMechanismSchema,
          conceptMetaphorSource: conceptMetaphorSourceSchema,
          rfpGrounding: { type: 'array', minItems: 3, maxItems: 5, items: { type: 'string' } },
          whyThisNameFitsRfp: { type: 'string' },
          whyThisIsNotJustPoetic: { type: 'string' },
          whyThisCanOrganizeProposal: { type: 'string' },
          whyThisNameWorks: { type: 'string' },
          conceptKeywords: { type: 'array', minItems: 3, maxItems: 3, items: { type: 'string' } },
          keywordExecutionGuide: { type: 'array', minItems: 3, maxItems: 3, items: keywordExecutionGuideSchema },
          experienceNarrativeFlow: { type: 'array', minItems: 3, items: { type: 'string' } },
          antiPatternValidation: antiPatternValidationSchema,
          mainStrength: { type: 'string' },
          mainRisk: { type: 'string' },
          entityDifferentiationUse: entityDifferentiationUseSchema,
          conceptRationale: conceptRationaleSchema,
          conceptTitle: { type: 'string' },
          subtitle: { type: 'string' },
          conceptNameKR: { type: 'string' },
          conceptNameEN: { type: 'string' },
          conceptNameEnglish: { type: 'string' },
          conceptNameKoreanSubtitle: { type: 'string' },
          conceptSloganKorean: { type: 'string' },
          conceptSloganEnglish: { type: 'string' },
          conceptScopeValidation: conceptScopeValidationSchema,
          conceptNameScopeClassification: { type: 'string', enum: conceptNameScopeClassificationEnum },
          oneLineDefinition: { type: 'string' },
          coreMessage: { type: 'string' },
          thesisProof: { type: 'string' },
          experienceStructure: { type: 'string' },
          expectedAssets: stringArray,
          strengths: stringArray,
          risks: stringArray,
          evaluationSummary: { type: 'string' },
          experienceLogic: { type: 'string' },
          keyExperienceAssetDirection: { type: 'string' },
          targetRelevance: { type: 'string' },
          spatialApplication: { type: 'string' },
          mediaInteractionPotential: { type: 'string' },
          viralPotential: { type: 'string' },
          executionFeasibility: { type: 'string' },
          whyThisWorks: { type: 'string' },
          riskOrCaution: { type: 'string' },
          evaluationScores: conceptEvaluationScoresSchema,
          coveredEntities: stringArray,
          missingEntities: stringArray,
          dominantEntity: { type: 'string' },
          entityBalanceStatus: { type: 'string', enum: entityBalanceStatusEnum },
          dominantEntityInName: { type: 'string' },
          productSpecificNameDetected: { type: 'boolean' },
          coversWholeRfp: { type: 'boolean' },
          conceptNameEvidenceLevel: { type: 'string', enum: ['proposalLevel', 'entityLevel', 'contentDetail', 'referenceOnly'] },
          repairedName: { type: 'boolean' },
        },
        required: [
          'conceptId',
          'rfpConceptType',
          'secondaryRfpConceptTypes',
          'strategicDirectionType',
          'strategicDirectionLabel',
          'whatThisDirectionEmphasizes',
          'whenToChooseThisDirection',
          'directionSource',
          'failurePatternAvoided',
          'winningPatternUsed',
          'directionDebug',
          'proposalCoreConceptName',
          'proposalCoreConceptSlogan',
          'proposalCoreConceptDefinition',
          'winningThesisUse',
          'conceptLeap',
          'signatureProofIdea',
          'whyThisIsCoreConcept',
          'experiencePrinciple',
          'visitorJourney',
          'contentMediaImplication',
          'conceptName',
          'conceptSlogan',
          'conceptTagline',
          'conceptDefinition',
          'hiddenNeedResolved',
          'strategicApproach',
          'whyThisConcept',
          'conceptMechanism',
          'conceptMetaphorSource',
          'rfpGrounding',
          'whyThisNameFitsRfp',
          'whyThisIsNotJustPoetic',
          'whyThisCanOrganizeProposal',
          'whyThisNameWorks',
          'conceptKeywords',
          'keywordExecutionGuide',
          'experienceNarrativeFlow',
          'antiPatternValidation',
          'mainStrength',
          'mainRisk',
          'entityDifferentiationUse',
          'conceptRationale',
          'conceptTitle',
          'subtitle',
          'conceptNameKR',
          'conceptNameEN',
          'conceptNameEnglish',
          'conceptNameKoreanSubtitle',
          'conceptSloganKorean',
          'conceptSloganEnglish',
          'conceptScopeValidation',
          'conceptNameScopeClassification',
          'oneLineDefinition',
          'coreMessage',
          'thesisProof',
          'experienceStructure',
          'expectedAssets',
          'strengths',
          'risks',
          'evaluationSummary',
          'experienceLogic',
          'keyExperienceAssetDirection',
          'targetRelevance',
          'spatialApplication',
          'mediaInteractionPotential',
          'viralPotential',
          'executionFeasibility',
          'whyThisWorks',
          'riskOrCaution',
          'evaluationScores',
          'coveredEntities',
          'missingEntities',
          'dominantEntity',
          'entityBalanceStatus',
          'dominantEntityInName',
          'productSpecificNameDetected',
          'coversWholeRfp',
          'conceptNameEvidenceLevel',
          'repairedName',
        ],
      },
    },
    recommendation: {
      type: 'object',
      additionalProperties: false,
      properties: {
        recommendedConceptId: { type: 'string' },
        recommendedDirectionLabel: { type: 'string' },
        recommendationReason: { type: 'string' },
        otherDirectionsUsefulness: { type: 'string' },
        tradeOffSummary: { type: 'string' },
        whyNotOthers: { type: 'string' },
      },
      required: ['recommendedConceptId', 'recommendedDirectionLabel', 'recommendationReason', 'otherDirectionsUsefulness', 'tradeOffSummary', 'whyNotOthers'],
    },
  },
  required: ['hiddenNeeds', 'strategicApproach', 'entityDifferentiationMatrix', 'conceptDevelopmentLogic', 'concepts', 'recommendation'],
} as const;



const conceptNameOptionSchema = {
  type: 'object',
  additionalProperties: false,
  properties: {
    id: { type: 'string' },
    conceptName: { type: 'string' },
    languageMode: { type: 'string', enum: ['Korean', 'English', 'bilingual'] },
    koreanSubtitle: { type: 'string' },
    oneLineSlogan: { type: 'string' },
    shortMeaning: { type: 'string' },
    whyItFitsRfp: { type: 'string' },
    coverTitleScore: { type: 'number' },
    memorabilityScore: { type: 'number' },
    rfpSpecificityScore: { type: 'number' },
    expandabilityScore: { type: 'number' },
    risk: { type: 'string' },
    namingStyle: { type: 'string', enum: ['Direct strategic', 'Brand / sensory', 'Spatial / system', 'Symbolic', 'Global English / bilingual'] },
    mainRisk: { type: 'string' },
  },
  required: ['conceptName', 'languageMode', 'koreanSubtitle', 'oneLineSlogan', 'shortMeaning', 'whyItFitsRfp', 'coverTitleScore', 'memorabilityScore', 'rfpSpecificityScore', 'expandabilityScore', 'risk', 'namingStyle', 'mainRisk'],
} as const;

export const conceptNameOptionsJsonSchema = {
  type: 'object',
  additionalProperties: false,
  properties: {
    selectedDirectionId: { type: 'string' },
    options: { type: 'array', minItems: 8, maxItems: 12, items: conceptNameOptionSchema },
    recommendedOptionIndex: { type: 'number' },
    generationNote: { type: 'string' },
  },
  required: ['selectedDirectionId', 'options', 'recommendedOptionIndex', 'generationNote'],
} as const;
export const outlineJsonSchema = {
  type: 'object',
  additionalProperties: false,
  properties: {
    slides: {
      type: 'array',
      minItems: 20,
      maxItems: 60,
      items: {
        type: 'object',
        additionalProperties: false,
        properties: {
          slideNumber: { type: 'number' },
          slideType: { type: 'string' },
          slideTitle: { type: 'string' },
          slidePurpose: { type: 'string', enum: slidePurposeEnum },
          slideRole: { type: 'string' },
          relationToThesis: { type: 'string' },
          whyThisSlideExists: { type: 'string' },
          sourceEvidence: { type: 'array', items: { type: 'string' } },
          referenceAllowed: { type: 'boolean' },
          keyMessage: { type: 'string' },
          mainCopy: { type: 'string' },
          confirmNeededNote: { type: 'string' },
        },
        required: ['slideNumber', 'slideType', 'slideTitle', 'slidePurpose', 'slideRole', 'relationToThesis', 'whyThisSlideExists', 'sourceEvidence', 'referenceAllowed', 'keyMessage', 'mainCopy', 'confirmNeededNote'],
      },
    },
  },
  required: ['slides'],
} as const;


const productExperienceDetailSchema = {
  type: 'object',
  additionalProperties: false,
  properties: {
    productCode: { type: 'string' },
    productRole: { type: 'string' },
    coreValue: { type: 'string' },
    experienceTitle: { type: 'string' },
    oneLineExperience: { type: 'string' },
    visitorMission: { type: 'string' },
    visitorAction: { type: 'string' },
    systemResponse: { type: 'string' },
    mediaOrObject: { type: 'string' },
    spatialPlacement: { type: 'string' },
    outputOrReward: { type: 'string' },
    snsSharePoint: { type: 'string' },
    visualDirection: { type: 'string' },
    imagePlaceholder: { type: 'string' },
    diagramSuggestion: { type: 'string' },
  },
  required: [
    'productCode',
    'productRole',
    'coreValue',
    'experienceTitle',
    'oneLineExperience',
    'visitorMission',
    'visitorAction',
    'systemResponse',
    'mediaOrObject',
    'spatialPlacement',
    'outputOrReward',
    'snsSharePoint',
    'visualDirection',
    'imagePlaceholder',
    'diagramSuggestion',
  ],
} as const;

const keyExperienceAssetSchema = {
  type: 'object',
  additionalProperties: false,
  properties: {
    assetName: { type: 'string' },
    assetType: { type: 'string' },
    roleInProposal: { type: 'string' },
    visitorAction: { type: 'string' },
    experienceMechanism: { type: 'string' },
    spatialPlacement: { type: 'string' },
    mediaOrObject: { type: 'string' },
    outputOrReward: { type: 'string' },
    whyItMatters: { type: 'string' },
    visualDirection: { type: 'string' },
  },
  required: [
    'assetName',
    'assetType',
    'roleInProposal',
    'visitorAction',
    'experienceMechanism',
    'spatialPlacement',
    'mediaOrObject',
    'outputOrReward',
    'whyItMatters',
    'visualDirection',
  ],
} as const;

const experienceScenarioStepSchema = {
  type: 'object',
  additionalProperties: false,
  properties: {
    step: { type: 'string', enum: ['Entry', 'Select', 'Experience', 'Generate', 'Share', 'Exit'] },
    visitorAction: { type: 'string' },
    systemResponse: { type: 'string' },
    mediaOrObject: { type: 'string' },
    output: { type: 'string' },
    designNote: { type: 'string' },
  },
  required: ['step', 'visitorAction', 'systemResponse', 'mediaOrObject', 'output', 'designNote'],
} as const;


const referenceInsightSchema = {
  type: 'object',
  additionalProperties: false,
  properties: {
    referenceName: { type: 'string' },
    referenceType: { type: 'string' },
    whatToLearn: { type: 'string' },
    howToApply: { type: 'string' },
    caution: { type: 'string' },
    sourceEvidence: { type: 'string' },
    referenceAllowed: { type: 'boolean' },
  },
  required: ['referenceName', 'referenceType', 'whatToLearn', 'howToApply', 'caution', 'sourceEvidence', 'referenceAllowed'],
} as const;

export const slideContentJsonSchema = {
  type: 'object',
  additionalProperties: false,
  properties: {
    slides: {
      type: 'array',
      minItems: 1,
      maxItems: 60,
      items: {
        type: 'object',
        additionalProperties: false,
        properties: {
          slideNumber: { type: 'number' },
          slideType: { type: 'string' },
          slideTitle: { type: 'string' },
          slidePurpose: { type: 'string', enum: slidePurposeEnum },
          slideRole: { type: 'string' },
          relationToThesis: { type: 'string' },
          whyThisSlideExists: { type: 'string' },
          sourceEvidence: { type: 'array', items: { type: 'string' } },
          referenceAllowed: { type: 'boolean' },
          keyMessage: { type: 'string' },
          mainCopy: { type: 'string' },
          bodyBullets: { type: 'array', minItems: 3, maxItems: 7, items: { type: 'string' } },
          visualDirection: { type: 'string' },
          visitorAction: { type: 'string' },
          contentMechanism: { type: 'string' },
          spatialPlacement: { type: 'string' },
          mediaOrObject: { type: 'string' },
          outputOrReward: { type: 'string' },
          imagePlaceholder: { type: 'string' },
          visualPrompt: { type: 'string' },
          diagramSuggestion: { type: 'string' },
          productExperienceDetails: { type: 'array', items: productExperienceDetailSchema },
          keyExperienceAssets: { type: 'array', maxItems: 3, items: keyExperienceAssetSchema },
          experienceScenarioSteps: { type: 'array', items: experienceScenarioStepSchema },
          referenceInsights: { type: 'array', items: referenceInsightSchema },
          speakerNote: { type: 'string' },
          confirmNeededNote: { type: 'string' },
        },
        required: [
          'slideNumber',
          'slideType',
          'slideTitle',
          'slidePurpose',
          'slideRole',
          'relationToThesis',
          'whyThisSlideExists',
          'sourceEvidence',
          'referenceAllowed',
          'keyMessage',
          'mainCopy',
          'bodyBullets',
          'visualDirection',
          'visitorAction',
          'contentMechanism',
          'spatialPlacement',
          'mediaOrObject',
          'outputOrReward',
          'imagePlaceholder',
          'visualPrompt',
          'diagramSuggestion',
          'productExperienceDetails',
          'keyExperienceAssets',
          'experienceScenarioSteps',
          'referenceInsights',
          'speakerNote',
          'confirmNeededNote',
        ],
      },
    },
  },
  required: ['slides'],
} as const;
