const stringArray = { type: 'array', items: { type: 'string' } } as const;


const taskSectionSchema = {
  type: 'object',
  additionalProperties: false,
  properties: {
    taskId: { type: 'string' },
    taskTitle: { type: 'string' },
    phase: { type: 'string' },
    requiredDeliverables: stringArray,
    target: stringArray,
    keyRequirements: stringArray,
    referenceMentions: stringArray,
    existingAssets: stringArray,
    constraints: stringArray,
    kpi: stringArray,
    schedule: stringArray,
    confirmNeeded: stringArray,
  },
  required: [
    'taskId',
    'taskTitle',
    'phase',
    'requiredDeliverables',
    'target',
    'keyRequirements',
    'referenceMentions',
    'existingAssets',
    'constraints',
    'kpi',
    'schedule',
    'confirmNeeded',
  ],
} as const;



const productFeatureSchema = {
  type: 'object',
  additionalProperties: false,
  properties: {
    product: { type: 'string' },
    keyFeature: { type: 'string' },
    valueProposition: { type: 'string' },
  },
  required: ['product', 'keyFeature', 'valueProposition'],
} as const;

const numericInfoSchema = {
  type: 'object',
  additionalProperties: false,
  properties: {
    pastPerformance: stringArray,
    lessonLearned: stringArray,
    currentIssue: stringArray,
    targetKPI: stringArray,
    referenceMetric: stringArray,
    proposedMeasurement: stringArray,
  },
  required: ['pastPerformance', 'lessonLearned', 'currentIssue', 'targetKPI', 'referenceMetric', 'proposedMeasurement'],
} as const;

const proposalTypeEnum = ['basic', 'cheil', 'innocean', 'hyundai', 'mice_event_operation', 'conference_forum'] as const;
const proposalScopeTypeEnum = ['contentDevelopment', 'boothExhibition', 'experienceMarketing', 'brandActivation', 'operationOnly', 'designBuild', 'publicTender'] as const;

const analysisSectionSchema = {
  type: 'object',
  additionalProperties: false,
  properties: {
    rfpFact: stringArray,
    aiProposal: stringArray,
    confirmNeeded: stringArray,
  },
  required: ['rfpFact', 'aiProposal', 'confirmNeeded'],
} as const;

export const analysisJsonSchema = {
  type: 'object',
  additionalProperties: false,
  properties: {
    projectOverview: { type: 'string' },
    clientChallenge: { type: 'string' },
    taskSections: { type: 'array', items: taskSectionSchema },
    inferredProposalType: { type: 'string', enum: proposalTypeEnum },
    proposalTypeReasoning: { type: 'string' },
    proposalScopeTypes: { type: 'array', items: { type: 'string', enum: proposalScopeTypeEnum } },
    proposalStructureGuard: { type: 'string' },
    requiredDeliverables: stringArray,
    scopeOfWork: stringArray,
    evaluationCriteria: stringArray,
    requiredItems: stringArray,
    requiredScope: stringArray,
    referenceOnly: stringArray,
    existingAssets: stringArray,
    productInfo: stringArray,
    productFeatures: { type: 'array', items: productFeatureSchema },
    kpiObjectives: stringArray,
    numericInfo: numericInfoSchema,
    constraints: stringArray,
    schedule: stringArray,
    doNotTreatAsScope: stringArray,
    confirmNeeded: stringArray,
    targetInfo: { type: 'string' },
    spatialCondition: { type: 'string' },
    contentCondition: { type: 'string' },
    operationCondition: { type: 'string' },
    kpiScheduleConstraints: stringArray,
    missingInfo: stringArray,
    rfpRequirements: analysisSectionSchema,
    clientTask: analysisSectionSchema,
    targetSpaceContentOperation: analysisSectionSchema,
    kpiTimelineConstraints: analysisSectionSchema,
  },
  required: [
    'projectOverview',
    'clientChallenge',
    'taskSections',
    'inferredProposalType',
    'proposalTypeReasoning',
    'proposalScopeTypes',
    'proposalStructureGuard',
    'requiredDeliverables',
    'scopeOfWork',
    'evaluationCriteria',
    'requiredItems',
    'requiredScope',
    'referenceOnly',
    'existingAssets',
    'productInfo',
    'productFeatures',
    'kpiObjectives',
    'numericInfo',
    'constraints',
    'schedule',
    'doNotTreatAsScope',
    'confirmNeeded',
    'targetInfo',
    'spatialCondition',
    'contentCondition',
    'operationCondition',
    'kpiScheduleConstraints',
    'missingInfo',
    'rfpRequirements',
    'clientTask',
    'targetSpaceContentOperation',
    'kpiTimelineConstraints',
  ],
} as const;


const conceptDevelopmentLogicSchema = {
  type: 'object',
  additionalProperties: false,
  properties: {
    winningStrategyBrief: { type: 'string' },
    proposalThesis: { type: 'string' },
    experienceLogic: { type: 'string' },
    clientIntent: { type: 'string' },
    audienceTakeaway: { type: 'string' },
    strategicTension: { type: 'string' },
    conceptSeed: { type: 'string' },
    coreChallenge: { type: 'string' },
    targetInsight: { type: 'string' },
    brandOrProductValue: { type: 'string' },
    experienceOpportunity: { type: 'string' },
    strategicApproach: { type: 'string' },
    conceptNecessity: { type: 'string' },
    selectedConceptReason: { type: 'string' },
  },
  required: [
    'winningStrategyBrief',
    'proposalThesis',
    'experienceLogic',
    'clientIntent',
    'audienceTakeaway',
    'strategicTension',
    'conceptSeed',
    'coreChallenge',
    'targetInsight',
    'brandOrProductValue',
    'experienceOpportunity',
    'strategicApproach',
    'conceptNecessity',
    'selectedConceptReason',
  ],
} as const;

const conceptEvaluationScoresSchema = {
  type: 'object',
  additionalProperties: false,
  properties: {
    rfpFitScore: { type: 'number', minimum: 1, maximum: 5 },
    targetFitScore: { type: 'number', minimum: 1, maximum: 5 },
    differentiationScore: { type: 'number', minimum: 1, maximum: 5 },
    spatialFeasibilityScore: { type: 'number', minimum: 1, maximum: 5 },
    viralPotentialScore: { type: 'number', minimum: 1, maximum: 5 },
    operationFeasibilityScore: { type: 'number', minimum: 1, maximum: 5 },
  },
  required: [
    'rfpFitScore',
    'targetFitScore',
    'differentiationScore',
    'spatialFeasibilityScore',
    'viralPotentialScore',
    'operationFeasibilityScore',
  ],
} as const;

export const conceptCandidatesJsonSchema = {
  type: 'object',
  additionalProperties: false,
  properties: {
    conceptDevelopmentLogic: conceptDevelopmentLogicSchema,
    concepts: {
      type: 'array',
      minItems: 3,
      maxItems: 3,
      items: {
        type: 'object',
        additionalProperties: false,
        properties: {
          conceptId: { type: 'string' },
          conceptNameKR: { type: 'string' },
          conceptNameEN: { type: 'string' },
          oneLineDefinition: { type: 'string' },
          coreMessage: { type: 'string' },
          experienceLogic: { type: 'string' },
          keyExperienceAssetDirection: { type: 'string' },
          targetRelevance: { type: 'string' },
          spatialApplication: { type: 'string' },
          mediaInteractionPotential: { type: 'string' },
          viralPotential: { type: 'string' },
          executionFeasibility: { type: 'string' },
          whyThisWorks: { type: 'string' },
          riskOrCaution: { type: 'string' },
          evaluationScores: conceptEvaluationScoresSchema,
        },
        required: [
          'conceptId',
          'conceptNameKR',
          'conceptNameEN',
          'oneLineDefinition',
          'coreMessage',
          'experienceLogic',
          'keyExperienceAssetDirection',
          'targetRelevance',
          'spatialApplication',
          'mediaInteractionPotential',
          'viralPotential',
          'executionFeasibility',
          'whyThisWorks',
          'riskOrCaution',
          'evaluationScores',
        ],
      },
    },
    recommendation: {
      type: 'object',
      additionalProperties: false,
      properties: {
        recommendedConceptId: { type: 'string' },
        recommendationReason: { type: 'string' },
        whyNotOthers: { type: 'string' },
      },
      required: ['recommendedConceptId', 'recommendationReason', 'whyNotOthers'],
    },
  },
  required: ['conceptDevelopmentLogic', 'concepts', 'recommendation'],
} as const;

export const outlineJsonSchema = {
  type: 'object',
  additionalProperties: false,
  properties: {
    slides: {
      type: 'array',
      minItems: 20,
      maxItems: 60,
      items: {
        type: 'object',
        additionalProperties: false,
        properties: {
          slideNumber: { type: 'number' },
          slideType: { type: 'string' },
          slideTitle: { type: 'string' },
          slidePurpose: { type: 'string' },
          keyMessage: { type: 'string' },
          mainCopy: { type: 'string' },
          confirmNeededNote: { type: 'string' },
        },
        required: ['slideNumber', 'slideType', 'slideTitle', 'slidePurpose', 'keyMessage', 'mainCopy', 'confirmNeededNote'],
      },
    },
  },
  required: ['slides'],
} as const;


const productExperienceDetailSchema = {
  type: 'object',
  additionalProperties: false,
  properties: {
    productCode: { type: 'string' },
    productRole: { type: 'string' },
    coreValue: { type: 'string' },
    experienceTitle: { type: 'string' },
    oneLineExperience: { type: 'string' },
    visitorMission: { type: 'string' },
    visitorAction: { type: 'string' },
    systemResponse: { type: 'string' },
    mediaOrObject: { type: 'string' },
    spatialPlacement: { type: 'string' },
    outputOrReward: { type: 'string' },
    snsSharePoint: { type: 'string' },
    visualDirection: { type: 'string' },
    imagePlaceholder: { type: 'string' },
    diagramSuggestion: { type: 'string' },
  },
  required: [
    'productCode',
    'productRole',
    'coreValue',
    'experienceTitle',
    'oneLineExperience',
    'visitorMission',
    'visitorAction',
    'systemResponse',
    'mediaOrObject',
    'spatialPlacement',
    'outputOrReward',
    'snsSharePoint',
    'visualDirection',
    'imagePlaceholder',
    'diagramSuggestion',
  ],
} as const;

const keyExperienceAssetSchema = {
  type: 'object',
  additionalProperties: false,
  properties: {
    assetName: { type: 'string' },
    assetType: { type: 'string' },
    roleInProposal: { type: 'string' },
    visitorAction: { type: 'string' },
    experienceMechanism: { type: 'string' },
    spatialPlacement: { type: 'string' },
    mediaOrObject: { type: 'string' },
    outputOrReward: { type: 'string' },
    whyItMatters: { type: 'string' },
    visualDirection: { type: 'string' },
  },
  required: [
    'assetName',
    'assetType',
    'roleInProposal',
    'visitorAction',
    'experienceMechanism',
    'spatialPlacement',
    'mediaOrObject',
    'outputOrReward',
    'whyItMatters',
    'visualDirection',
  ],
} as const;

const experienceScenarioStepSchema = {
  type: 'object',
  additionalProperties: false,
  properties: {
    step: { type: 'string', enum: ['Entry', 'Select', 'Experience', 'Generate', 'Share', 'Exit'] },
    visitorAction: { type: 'string' },
    systemResponse: { type: 'string' },
    mediaOrObject: { type: 'string' },
    output: { type: 'string' },
    designNote: { type: 'string' },
  },
  required: ['step', 'visitorAction', 'systemResponse', 'mediaOrObject', 'output', 'designNote'],
} as const;


const referenceInsightSchema = {
  type: 'object',
  additionalProperties: false,
  properties: {
    referenceName: { type: 'string' },
    referenceType: { type: 'string' },
    whatToLearn: { type: 'string' },
    howToApply: { type: 'string' },
    caution: { type: 'string' },
  },
  required: ['referenceName', 'referenceType', 'whatToLearn', 'howToApply', 'caution'],
} as const;

export const slideContentJsonSchema = {
  type: 'object',
  additionalProperties: false,
  properties: {
    slides: {
      type: 'array',
      minItems: 1,
      maxItems: 60,
      items: {
        type: 'object',
        additionalProperties: false,
        properties: {
          slideNumber: { type: 'number' },
          slideType: { type: 'string' },
          slideTitle: { type: 'string' },
          slidePurpose: { type: 'string' },
          keyMessage: { type: 'string' },
          mainCopy: { type: 'string' },
          bodyBullets: { type: 'array', minItems: 3, maxItems: 7, items: { type: 'string' } },
          visualDirection: { type: 'string' },
          visitorAction: { type: 'string' },
          contentMechanism: { type: 'string' },
          spatialPlacement: { type: 'string' },
          mediaOrObject: { type: 'string' },
          outputOrReward: { type: 'string' },
          imagePlaceholder: { type: 'string' },
          visualPrompt: { type: 'string' },
          diagramSuggestion: { type: 'string' },
          productExperienceDetails: { type: 'array', items: productExperienceDetailSchema },
          keyExperienceAssets: { type: 'array', maxItems: 3, items: keyExperienceAssetSchema },
          experienceScenarioSteps: { type: 'array', items: experienceScenarioStepSchema },
          referenceInsights: { type: 'array', items: referenceInsightSchema },
          speakerNote: { type: 'string' },
          confirmNeededNote: { type: 'string' },
        },
        required: [
          'slideNumber',
          'slideType',
          'slideTitle',
          'slidePurpose',
          'keyMessage',
          'mainCopy',
          'bodyBullets',
          'visualDirection',
          'visitorAction',
          'contentMechanism',
          'spatialPlacement',
          'mediaOrObject',
          'outputOrReward',
          'imagePlaceholder',
          'visualPrompt',
          'diagramSuggestion',
          'productExperienceDetails',
          'keyExperienceAssets',
          'experienceScenarioSteps',
          'referenceInsights',
          'speakerNote',
          'confirmNeededNote',
        ],
      },
    },
  },
  required: ['slides'],
} as const;
